### ISSUE TITLE
cookie 'connect.sid' required

### ISSUE THREAD

**Issue by hallveticapro** [UnderwaterOverground/Plex-Concierge#1]
Not sure if this is something you'd be able to assist with but, when setting this up, everything goes smoothly until I actually try to use it. At that point, I get the following error:

`
{
  "response_data": {
    "message": "cookie 'connect.sid' required",
    "errors": [
      {
        "path": "/api/v1/search",
        "message": "cookie 'connect.sid' required"
      }
    ]
  },
  "status_code": 401
}
`

with the ChatGPT output telling me

`
The request could not be completed because a required cookie (connect.sid) is missing. This appears to be a technical issue with the API setup. Let me know how you'd like to proceed.
`

I have my API key from Overseerr configured in the Action and I've tried adjusting the Auth Type from Basic to Bearer but not having any success.

**Comment by hallveticapro** [comment]
Issue resolved! I had to adjust the API key authentication type to Custom with `X-Api-Key` as the parameter. Now it's all working as it should!

**Comment by grostim** [comment]
Thanks for the tip !

This would deserve an update in Readme.md .
